[goldmark]
  [goldmark.renderer]
    hardWraps = false
    # change to false to disable inclusion of rawHTML and math functions
    unsafe = true
    xhtml = false
  [goldmark.extensions]
    typographer = false
  [highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    # always set to true # else line numbers won't show at all!
    # even when you toggle them on in the UI
    lineNos = true
    # toggling this on (i.e to true) or deleting this line will break the code blocks functionality.
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2
