[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "C++"
url = ""
weight = -109

[[main]]
parent = "C++"
name = "Clang-Tidy"
url = "post/cpp/clang-tidy/clang-tidy"

[[main]]
parent = "C++"
name = "C++ Core Guidelines"
url = "post/cpp/cpp-core-guidelines/cpp-core-guidelines"

[[main]]
parent = "C++"
name = "More C++ Idioms"
url = "post/cpp/more-cpp-idioms/more-cpp-idioms"

[[main]]
name = "About"
url = "about/"
weight = -108

[[social]]
name = "github"
type = "social"
weight = 1
url = "https://github.com/ba7lya"

[[social]]
name = "rss"
type = "social"
weight = 4
url = "index.xml"
