[[main]]
  name = "Home"
  url = ""
  weight = -110

# [[main]]
#   name = "Archives"
#   url = "post/rich-content/"
#   weight = -109

# Submenus are done this way: parent -> identifier

# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ba7lya"
[[social]]
  name = "rss"
  type = "social"
  weight = 4
  url = "index.xml"