[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "C++ Best Practices"
url = ""
weight = -109

[[main]]
parent = "C++ Best Practices"
name = "Clang-Tidy"
url = "post/cpp/clang-tidy/clang-tidy"

[[main]]
parent = "C++ Best Practices"
name = "C++ Sanitizer"
url = ""

[[main]]
parent = "C++ Best Practices"
name = "C++ Core Guidelines"
url = "post/cpp/cpp-core-guidelines/cpp-core-guidelines"

[[main]]
name = "Design Pattern"
url = ""
weight = -108

[[main]]
parent = "Design Pattern"
name = "Architectural Patterns"
url = "post/cpp/more-cpp-idioms/more-cpp-idioms"

[[main]]
parent = "Design Pattern"
name = "Concurrency Patterns"
url = "post/cpp/more-cpp-idioms/more-cpp-idioms"

[[main]]
parent = "Design Pattern"
name = "Design Patterns"
url = "post/cpp/more-cpp-idioms/more-cpp-idioms"

[[main]]
parent = "Design Pattern"
name = "Idioms"
url = "post/cpp/more-cpp-idioms/more-cpp-idioms"

[[main]]
name = "Algorithm"
url = ""
weight = -107

[[main]]
name = "C++ Libraries"
url = ""
weight = -106

[[main]]
name = "About"
url = "about/"
weight = -105

[[social]]
name = "github"
type = "social"
weight = 1
url = "https://github.com/ba7lya"

[[social]]
name = "rss"
type = "social"
weight = 4
url = "index.xml"
