[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "C++"
  url = ""
  weight = -109
[[main]]
  parent = "C++"
  name = "Clang-Tidy"
  url = "post/clang-tidy/clang-tidy"
[[main]]
  parent = "C++"
  name = "C++ Core Guidelines"
  url = "post/cpp-core-guidelines/cpp-core-guidelines"

[[main]]
  name = "About"
  url = "about/"
  weight = -108

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ba7lya"
[[social]]
  name = "rss"
  type = "social"
  weight = 4
  url = "index.xml"